In [1]:
#데이터 불러오기
from petitions_dataset import Petitions

petitions = Petitions("C:/Users/myunghoon_k/OneDrive - 서울시립대학교/bitamin/NLP_summer/nlp_bitamin/petitions_data",
                     begin_date = '2018-01-01', end_date = '2018-12-31')

ModuleNotFoundError: No module named 'petitions_dataset'

In [ ]:
len(petitions)

In [ ]:
#불러올 데이터의 키 설정
petitions.set_keys('begin', 'end', 'category', 'title', 'content','num_agree')

In [ ]:
petitions.keys

In [ ]:
result = []
for begin, end, category, title, content, num_agree in petitions:
    temp = []
    temp.append(begin)
    temp.append(end)
    temp.append(category)
    temp.append(title)
    temp.append(content)
    temp.append(num_agree)
    result.append(temp)

In [ ]:
result[10]

In [ ]:
import pandas as pd

df_raw = pd.DataFrame(result, columns = ['begin', 'end', 'category', 'title', 'content',
        'num_agree'])

In [14]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 298459 entries, 0 to 298458
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   begin      298459 non-null  object
 1   end        298459 non-null  object
 2   category   298459 non-null  object
 3   title      298459 non-null  object
 4   content    298459 non-null  object
 5   num_agree  298459 non-null  int64 
dtypes: int64(1), object(5)
memory usage: 13.7+ MB


In [16]:
df_raw.head()

begin         end  category  \
0  2018-01-01  2018-01-31        행정   
1  2018-01-01  2018-01-31        기타   
2  2018-01-01  2018-01-31      정치개혁   
3  2018-01-01  2018-01-31    인권/성평등   
4  2018-01-01  2018-01-31  외교/통일/국방   

                                             title  \
0                         아...이런데서 이상한 글이 올라오네요...   
1  현재 사람들 사이에서 유행하는 게임 "배틀 그라운드" 에 대한 제재를 가하려 합니다.   
2                                  양심수 석방 국가보안법 철폐   
3                          민주화유공자들에 대한 국가유공자 인정 요청   
4                                           UAE 관련   

                                             content  num_agree  
0  이런 국민청원하는 게시판에서 뭐 섹스,희주야'''''이런 이상한 글 올라오는데 여기...          6  
1  "배틀 그라운드"는 현재 세계적으로나 우리나라 에서나 매우 흥행 하는 게임입니다. ...          1  
2  적폐청산의 시금석 양심수들의 특별사면 배제 문재인 정부를 규탄한다. 지난 12월 2...          0  
3  안녕하세요. 살벌한 독재시대를 떠나, 대한민국 민주화를 이룩하신 수많은 열사들이, ...          3  
4  Uae 괸련한 야당 질의와 관련하여 기본적으로 유시민 작가의 말씀에 동의하여 국익에...          0

In [59]:
df_raw.sort_values('num_agree', ascending = False)

begin         end     category  \
240334  2018-10-17  2018-11-16        안전/환경   
135650  2018-06-13  2018-07-13     외교/통일/국방   
46689   2018-02-19  2018-03-21  문화/예술/체육/언론   
111036  2018-05-11  2018-06-10       인권/성평등   
254766  2018-10-31  2018-11-30       인권/성평등   
...            ...         ...          ...   
90441   2018-04-16  2018-05-16           행정   
210630  2018-09-05  2018-10-05     교통/건축/국토   
90417   2018-04-16  2018-05-16           미래   
210658  2018-09-05  2018-10-05     외교/통일/국방   
227551  2018-09-27  2018-10-27           기타   

                                                    title  \
240334                      강서구 피시방 살인 사건. 또 심신미약 피의자입니다.   
135650  제주도 불법 난민 신청 문제에 따른 난민법, 무사증 입국, 난민신청허가 폐지/개헌 ...   
46689            김보름, 박지우 선수의 자격박탈과 적폐 빙상연맹의 엄중 처벌을 청원합니다   
111036             여성도 대한민국 국민입니다. 성별 관계없는 국가의 보호를 요청합니다.   
254766  132cm, 31kg의 왜소한 50대 여성이 180cm가 넘는 건장한 20세 남성에...   
...                                                   ...   
90441                               국민체육진흥공당 케이토토 클린통합콜센터   
210630       여수시 신월동소재 (주) 한화 사업장 도로 개방을 통한 차량 통행 요청 드립니다   
90417             프렌차이즈 대표 갑질보다 무서운 프렌차이즈 직원들 비리[치킨값좀내리자]   
210658                경도지체장애를 판정후 전역한 장병들을 국가유공자등록을 청원합니다   
227551                   경찰관이 개인사적인 일을 알아내려고 개인정보를 조회합니다!   

                                                  content  num_agree  \
240334                                                       1192049   
135650                                                        714875   
46689                                                         614127   
111036                                                        419006   
254766                                                        416093   
...                                                   ...        ...   
90441   https://cleansports.kspo.or.kr/cleansports/mai...          0   
210630  여수시 (주) 한화 사업장 도로 개방을 통해 차량 통행이 가능 하도록 요청드립니다 ...          0   
90417   치킨 값이 또 오른다니 짜증나고 짜증 납니다. 1000~1500원짜리 닭이 우리가 ...          0   
210658  안녕하세요..저는 2008년 경도지체장애를 발병하여 전역한 자입니다 2011년에 소...          0   
227551  공적 업무에 필요시 조회되어야 할 개인정보를 평택에서 근무하는 채지현 경장(91년생...          0   

        new_status  
240334           1  
135650           1  
46689            1  
111036           1  
254766           1  
...            ...  
90441            0  
210630           0  
90417            0  
210658           0  
227551           0  

[298459 rows x 7 columns]

In [20]:
#20만을 넘었는지 여부를 0,1로 표기하는 열 추가

mask = (df_raw.num_agree >= 200000)

df_raw['new_status'] = df_raw.num_agree.apply(lambda x: 1 if x >= 200000 else 0)

In [22]:
df_raw.new_status.value_counts()

0    298391
1        68
Name: new_status, dtype: int64

In [24]:
#전처리 시작1

#제목 이용 중복데이터 제거

#1) 시리즈를 리스트로
import re

raw_title = list(df_raw['title'])
raw_title[:10]

['아...이런데서 이상한 글이 올라오네요...',
 '현재 사람들 사이에서 유행하는 게임 "배틀 그라운드" 에 대한 제재를 가하려 합니다.',
 '양심수 석방 국가보안법 철폐',
 '민주화유공자들에 대한 국가유공자 인정 요청',
 'UAE 관련',
 '칼퇴근법 하루 빨리 시행되었으면 합니다',
 '빠른년생을 위한 법 개정',
 '다주택자만 문제일까요?',
 '가정폭력 처벌 수위를 강화해주세요',
 '10년공공임대분양가를 5년공공임대 분양전환 산정방식과 동일하게 변경해 주세요.']

In [25]:
raw_title[0].split()

['아...이런데서', '이상한', '글이', '올라오네요...']

In [26]:
#제목변형 정규표현식
result = []

for text in raw_title:
    text_sp = text.split() #문자열들을 띄어씌기 기준으로 구분하여 리스트를 생성
    text_join = ''.join(text_sp) #리스트안의 문자열들을 하나의 문자열로 생성
    text_sub = re.sub(r'[,$()*+.?[\^{|]+', '', text_join) #문자열 안의 특수문자 제거
    result += [text_sub] #result 리스트안에 하나씩 변환된 제목들을 쌓기

In [27]:
len(result) #문서의 개수와 일치

298459

In [32]:
#df_raw를 복사한 데이터프레임 객체 생성
df2 = df_raw.copy()
df2['mod_title'] = result

In [33]:
df2.head()

begin         end  category  \
0  2018-01-01  2018-01-31        행정   
1  2018-01-01  2018-01-31        기타   
2  2018-01-01  2018-01-31      정치개혁   
3  2018-01-01  2018-01-31    인권/성평등   
4  2018-01-01  2018-01-31  외교/통일/국방   

                                             title  \
0                         아...이런데서 이상한 글이 올라오네요...   
1  현재 사람들 사이에서 유행하는 게임 "배틀 그라운드" 에 대한 제재를 가하려 합니다.   
2                                  양심수 석방 국가보안법 철폐   
3                          민주화유공자들에 대한 국가유공자 인정 요청   
4                                           UAE 관련   

                                             content  num_agree  new_status  \
0  이런 국민청원하는 게시판에서 뭐 섹스,희주야'''''이런 이상한 글 올라오는데 여기...          6           0   
1  "배틀 그라운드"는 현재 세계적으로나 우리나라 에서나 매우 흥행 하는 게임입니다. ...          1           0   
2  적폐청산의 시금석 양심수들의 특별사면 배제 문재인 정부를 규탄한다. 지난 12월 2...          0           0   
3  안녕하세요. 살벌한 독재시대를 떠나, 대한민국 민주화를 이룩하신 수많은 열사들이, ...          3           0   
4  Uae 괸련한 야당 질의와 관련하여 기본적으로 유시민 작가의 말씀에 동의하여 국익에...          0           0   

                             mod_title  
0                      아이런데서이상한글이올라오네요  
1  현재사람들사이에서유행하는게임"배틀그라운드"에대한제재를가하려합니다  
2                         양심수석방국가보안법철폐  
3                  민주화유공자들에대한국가유공자인정요청  
4                                UAE관련

In [34]:
#drop+duplicates 이용 중복제목 제거
df2.drop_duplicates(subset = ['mod_title'], inplace = True)
df2.shape #중복 제목 제거 완료

(270971, 8)

In [55]:
print('중복 제거 결과 삭제된 문서의 수:', df_raw.shape[0] - df2.shape[0])

중복 제거 결과 삭제된 문서의 수: 27488


In [96]:
#작업한 내용 저장
df2.to_pickle('petitions_df2_ppt.pkl')
    #pkl파일형식으로 저장해서 불러오면 지금과 같은 데이터프레임 생성 및 전처리 작업을
    #따로 하지않아도 기존의 저장된 데이터프레임을 그대로 사용할 수 있음!

In [45]:
#컨텐츠 내용 전처리 작업

    #아래와 같이 특수문자가 존재하는 게시물 존재
    #특수문자나 그 외의 필요없는 문자들은 이후 사용하는 형태소분석기의 성능을 떨어뜨림
df2.iloc[260, 4]

'■ 평창 동계올림픽 성공기원 제안 1. 개요 평창 동계올림픽을 앞두고 논란이 되고 있는 문제점에 대해 국가적 이미지 손실을 방지하고 개선하는데 취지가 있음 2. 문제점 □ 지역내 한철주의 상술로 인한 불쾌감 - 숙박, 식당, 기타 편의시설에 대한 극심한 바가지 예상 - 평창 홍보 및 올림픽 소식의 일선인 무선 통신의 제한(과중한 요금) - 업소 뿐만 아니라 일부 지역주민의 한탕 주의 전염 □ 강원도 특성의 교통 문제 - 국내 관광객도 자차 또는 택시를 이용해야 할 만큼 교통 인프라 부족 - 홈페이지를 통해 인근지역 경로를 안내하고 있으나 개별 단위 외국인 관광객에게는 불편함 예상 □ 비인기 종목에 대한 관람 미달로 운영비 적자 예상 - 상권 및 편의시설 사용 빈도 저하 3. 대책안 □ 군장병 가이드 네트워크 가동 - 강원도 인근 이수지역 군부대를 중심으로 통역이 가능한 군장병 선발 (지역확대가능) - 1차 통역 중심 선발, 2차 세부 교육 과정을 통해 약 일천명 선발 □ 교육과정 - 외국인 가이드 중점으로 교통, 숙박, 먹거리등 관광 중심 편의 과정 - 원활한 서비스 제공을 위한 가이드 예절 및 안보 - 가이드 장비 사용 및 인프라 과정 (별도 설명) □ 가이드 인프라 구축 - 선발인원을 중심으로 인근 지역 착한 업소 선정 및 교통 가이드 등록 (1시간 내 거리/관할 구청 협조) - 선정된 업소는 올림픽 홍보부서 주관으로 관광 가이드 네트워크에 등록 (가격, 교통제공, 매뉴 등) - 등록 사항은 홍보 앱을 통해 행사 기간 내 업데이트가 가능토록 조치 □ 가이드 통신 지원 - 군장병 특성상 원활한 통신을 위해 국내 기업 으로 부터 최신폰을 지원 받고 무제한 데이터제공 (가이드 네트워크 사용 필요) - 와이파이 핫스팟연동 - 관광객은 무제한으로 무선 서비스를 자유롭게 이용, 자연스럽게 국내 최신폰 홍보 □ 가이드 위반 조치 - 행사기간 내 서비스 불친절 및 단가 변동 업소는 즉시 업로드 하여 관할 구청으로부터 행정 처분 - 가이드의 금품 요구 및 부적절 행위 에

In [47]:
#한국 불용어 목록 불러오기
#다음의 페이지에서 참조함
#https://www.ranks.nl/stopwords/korean
#https://bab2min.tistory.com/544

stopwords_kr = pd.read_csv("C:/Users/myunghoon_k/OneDrive - 서울시립대학교/bitamin/NLP_summer/nlp_bitamin/stopwords_kr.txt",
                          sep = '\n', header = None)
stop_kr_list = list(stopwords_kr.iloc[:,0])

In [50]:
#전체 텍스트 전처리 시도
#전처리하고자 하는 내용을 담은 사용자 정의 함수 실행
#https://regex101.com/ 

url_with_https = re.compile(r'(https?:\/\/){1,}([\w.\/%-]+){1,}')
rm_email = re.compile(r'([a-zA-Z0-9\.\_]+)@([\w\.]+){1,}')
useless_words = re.compile(r'[\(\)\"\'\∎\■\□\=\-\<\>\★\○]+')
rm_num = re.compile(r'([^\w]?\d+\.?\,?\)?\d*)+')

def clean_kor_text(kor_text):
    text = url_with_https.sub('',kor_text)
    text = rm_email.sub('', text)
    text = useless_words.sub('',text)
    text = rm_num.sub('',text)
    text = ' '.join(word for word in text.split() if word not in stop_kr_list)
    return text

df2['mod_content'] = df2['content'].apply(clean_kor_text)

In [51]:
df2.iloc[260, -1]
    #특수문자와 괄호가 사라진것을 알 수 있음!
    #숫자역시 지워진 것을 알 수 있음

'평창 동계올림픽 성공기원 제안 개요 평창 동계올림픽을 앞두고 논란이 되고 있는 문제점에 대해 국가적 이미지 손실을 방지하고 개선하는데 취지가 있음 문제점 지역내 한철주의 상술로 인한 불쾌감 숙박, 식당, 편의시설에 대한 극심한 바가지 예상 평창 홍보 올림픽 소식의 일선인 무선 통신의 제한과중한 요금 업소 뿐만 아니라 일부 지역주민의 한탕 주의 전염 강원도 특성의 교통 문제 국내 관광객도 자차 또는 택시를 이용해야 할 만큼 교통 인프라 부족 홈페이지를 통해 인근지역 경로를 안내하고 있으나 개별 단위 외국인 관광객에게는 불편함 예상 비인기 종목에 대한 관람 미달로 운영비 적자 예상 상권 편의시설 사용 빈도 저하 대책안 군장병 가이드 네트워크 가동 강원도 인근 이수지역 군부대를 중심으로 통역이 가능한 군장병 선발 지역확대가능 차 통역 중심 선발,차 세부 교육 과정을 통해 약 일천명 선발 교육과정 외국인 가이드 중점으로 교통, 숙박, 먹거리등 관광 중심 편의 과정 원활한 서비스 제공을 위한 가이드 예절 안보 가이드 장비 사용 인프라 과정 별도 설명 가이드 인프라 구축 선발인원을 중심으로 인근 지역 착한 업소 선정 교통 가이드 등록시간 내 거리/관할 구청 협조 선정된 업소는 올림픽 홍보부서 주관으로 관광 가이드 네트워크에 등록 가격, 교통제공, 매뉴 등록 사항은 홍보 앱을 통해 행사 기간 내 업데이트가 가능토록 조치 가이드 통신 지원 군장병 특성상 원활한 통신을 위해 국내 기업 최신폰을 지원 받고 무제한 데이터제공 가이드 네트워크 사용 필요 와이파이 핫스팟연동 관광객은 무제한으로 무선 서비스를 자유롭게 이용, 자연스럽게 국내 최신폰 홍보 가이드 위반 조치 행사기간 내 서비스 불친절 단가 변동 업소는 업로드 하여 관할 구청으로부터 행정 처분 가이드의 금품 요구 부적절 행위 대해 신고 기능 제공 기대효과 관광객의 예상되는 불편함을 군장병 가이드를 통해 신뢰 편리함 제공 관광객의 SNS활동으로 참여 업소는 국내외 홍보 효과 가능 관광지 특성상 일부 비양심 업자를 소멸 하고

In [52]:
df2.drop('end', axis = 1, inplace = True)
cols = ['begin', 'category', 'title', 'mod_content', 'num_agree', 'new_status']
df2 = df2[cols]

In [53]:
df2.head()

begin  category                                            title  \
0  2018-01-01        행정                         아...이런데서 이상한 글이 올라오네요...   
1  2018-01-01        기타  현재 사람들 사이에서 유행하는 게임 "배틀 그라운드" 에 대한 제재를 가하려 합니다.   
2  2018-01-01      정치개혁                                  양심수 석방 국가보안법 철폐   
3  2018-01-01    인권/성평등                          민주화유공자들에 대한 국가유공자 인정 요청   
4  2018-01-01  외교/통일/국방                                           UAE 관련   

                                         mod_content  num_agree  new_status  
0  국민청원하는 게시판에서 뭐 섹스,희주야이런 이상한 글 올라오는데 여기는 청원하는데지...          6           0  
1  배틀 그라운드는 현재 세계적으로나 우리나라 에서나 매우 흥행 하는 게임입니다. 게임...          1           0  
2  적폐청산의 시금석 양심수들의 특별사면 배제 문재인 정부를 규탄한다. 지난월일 문재인...          0           0  
3  안녕하세요. 살벌한 독재시대를 떠나, 대한민국 민주화를 이룩하신 수많은 열사들이, ...          3           0  
4  Uae 괸련한 야당 질의와 관련하여 기본적으로 유시민 작가의 말씀에 동의하여 국익에...          0           0

In [60]:
#20만개 이상의 경우에 내용이 있는지 없는지 확인
#공백내용이 있는 행 제거
df2.reset_index(drop = True, inplace = True)
df2.sort_values(by = 'num_agree', ascending = False)

begin     category  \
219423  2018-10-17        안전/환경   
123058  2018-06-13     외교/통일/국방   
41695   2018-02-19  문화/예술/체육/언론   
100345  2018-05-11       인권/성평등   
232090  2018-10-31       인권/성평등   
...            ...          ...   
17339   2018-01-20           기타   
81831   2018-04-16        안전/환경   
81828   2018-04-16           기타   
249060  2018-11-23         농산어촌   
65648   2018-03-24         정치개혁   

                                                    title  \
219423                      강서구 피시방 살인 사건. 또 심신미약 피의자입니다.   
123058  제주도 불법 난민 신청 문제에 따른 난민법, 무사증 입국, 난민신청허가 폐지/개헌 ...   
41695            김보름, 박지우 선수의 자격박탈과 적폐 빙상연맹의 엄중 처벌을 청원합니다   
100345             여성도 대한민국 국민입니다. 성별 관계없는 국가의 보호를 요청합니다.   
232090  132cm, 31kg의 왜소한 50대 여성이 180cm가 넘는 건장한 20세 남성에...   
...                                                   ...   
17339                            문제해결한 사람이 대접받는 사회시스템구축요망   
81831                           가스공사 가스안전공사 독과점 개선 요청합니다.   
81828                                  춘천지검의 특별감사를 청원합니다.   
249060                                    부산 기장군 철마면 입니다.   
65648                           문재인대통령님대한민국이라는나라를좀힘들게해주세요   

                                              mod_content  num_agree  \
219423                                                       1192049   
123058                                                        714875   
41695                                                         614127   
100345                                                        419006   
232090                                                        416093   
...                                                   ...        ...   
17339   문제해결한 사람이 대접받는 사회시스템구축요망 민주주의에 공헌주의를 결합해야 합니다....          0   
81831   제목과 가스 분야 독과점 완화 요청합니다.가격책정부터 가스관련된 모든것을 처리 일부...          0   
81828   스카니아 차량의 제작결함 은폐로 운전자는 차량결함으로 인하여 대형사고뿐아니라 목숨을...          0   
249060  기장군 철마면 주민인데요. 철마면 이곡리 지역 포함 해서요,,, 지역이 부산광역시의...          0   
65648             문재인대통령님 대한민국이라는나라를좀힘들게해주세요 부탁드립니다 존경합니다          0   

        new_status  
219423           1  
123058           1  
41695            1  
100345           1  
232090           1  
...            ...  
17339            0  
81831            0  
81828            0  
249060           0  
65648            0  

[270971 rows x 6 columns]

In [64]:
len(df2.iloc[232090,3])

0

In [67]:
df2['cont_lne'] = df2.mod_content.apply(lambda x: len(x))

In [72]:
mask2 = (df2.cont_lne >  0)
df3 = df2.loc[mask2]

In [73]:
df3.shape

(270836, 7)

In [56]:
#명사 태깅
from eunjeon import Mecab 
m = Mecab(dicpath='C:/mecab/mecab-ko-dic')

In [74]:
#데이터프레임에 apply하기 위한 함수 생성
def get_nouns(doc):
    return m.nouns(doc)

In [77]:
#명사 태킹 작업용 인덱스 리스트 생성
slice_list_final= [i for i in range(0, df3.index[-1], 10000)]
    #매 10000번마다 태깅이 이뤄지도록 기준 인덱스들을 생성
len(slice_list_final)

28

In [78]:
slice_list_final

[0,
 10000,
 20000,
 30000,
 40000,
 50000,
 60000,
 70000,
 80000,
 90000,
 100000,
 110000,
 120000,
 130000,
 140000,
 150000,
 160000,
 170000,
 180000,
 190000,
 200000,
 210000,
 220000,
 230000,
 240000,
 250000,
 260000,
 270000]

In [82]:
for i in range(len(slice_list_final)-1):
    if i < 26:
        print(slice_list_final[i], slice_list_final[i+1])
    else:
        print(slice_list_final[i], df3.index[-1])

0 10000
10000 20000
20000 30000
30000 40000
40000 50000
50000 60000
60000 70000
70000 80000
80000 90000
90000 100000
100000 110000
110000 120000
120000 130000
130000 140000
140000 150000
150000 160000
160000 170000
170000 180000
180000 190000
190000 200000
200000 210000
210000 220000
220000 230000
230000 240000
240000 250000
250000 260000
260000 270970


In [88]:
#명사태깅 실시
import numpy as np
import time

df3.reset_index(drop = True, inplace = True)
start_time = time.time()

result_cont = pd.Series(dtype = 'object') #빈시리즈 생성
for i in range(len(slice_list_final)-1):
    if i < 26:
        df3_f = df3.iloc[slice_list_final[i]:slice_list_final[i+1], 3]
        temp = df3_f.map(lambda x: get_nouns(x)) 
        result_cont = result_cont.append(temp, ignore_index = True)
    else:
        df3_f = df3.iloc[slice_list_final[i]:, 3]
        temp = df3_f.map(lambda x: get_nouns(x))
        result_cont = result_cont.append(temp, ignore_index = True)

print('소요시간: ', np.round((time.time() - start_time) / 60, 2))
result_cont.shape
    #약 3분이 소요됨!

소요시간:  2.66


(270836,)

In [89]:
#명사 토큰화결과
result_cont 

0         [국민, 청원, 게시판, 섹스, 희, 주야, 이상, 글, 여기, 청원, 곳, 놈, ...
1         [배틀, 그라운드, 세계, 우리, 나라, 흥행, 게임, 게임, 청소년, 이용, 불가...
2         [적폐, 청산, 시금석, 양심수, 특별, 사면, 배제, 문재, 정부, 규탄, 월일,...
3         [안녕, 독재, 시대, 대한민국, 민주, 열사, 민주, 유공자, 인정, 국가, 유공...
4         [련, 야당, 질의, 관련, 기본, 유시민, 작가, 말씀, 동의, 국익, 관련, 정...
                                ...                        
270831    [공개, 거, 내용, 공개, 의역, 허위, 과장, 번, 핵, 거, 뻥, 연내, 답방...
270832                                             [엑소, 해체]
270833                                            [박근혜, 사면]
270834    [국방, 의무, 의도, 체중, 감량, 지인, 검, 희망, 의도, 체중, 감량, 급,...
270835    [학생, 부, 종합, 전형, 대학, 입시, 부분, 차지, 학생, 잠, 공부, 부족,...
Length: 270836, dtype: object

In [90]:
df3['cont_noun'] = result_cont
df3.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


begin  category                                            title  \
0  2018-01-01        행정                         아...이런데서 이상한 글이 올라오네요...   
1  2018-01-01        기타  현재 사람들 사이에서 유행하는 게임 "배틀 그라운드" 에 대한 제재를 가하려 합니다.   
2  2018-01-01      정치개혁                                  양심수 석방 국가보안법 철폐   
3  2018-01-01    인권/성평등                          민주화유공자들에 대한 국가유공자 인정 요청   
4  2018-01-01  외교/통일/국방                                           UAE 관련   

                                         mod_content  num_agree  new_status  \
0  국민청원하는 게시판에서 뭐 섹스,희주야이런 이상한 글 올라오는데 여기는 청원하는데지...          6           0   
1  배틀 그라운드는 현재 세계적으로나 우리나라 에서나 매우 흥행 하는 게임입니다. 게임...          1           0   
2  적폐청산의 시금석 양심수들의 특별사면 배제 문재인 정부를 규탄한다. 지난월일 문재인...          0           0   
3  안녕하세요. 살벌한 독재시대를 떠나, 대한민국 민주화를 이룩하신 수많은 열사들이, ...          3           0   
4  Uae 괸련한 야당 질의와 관련하여 기본적으로 유시민 작가의 말씀에 동의하여 국익에...          0           0   

   cont_lne                                          cont_noun  
0        90  [국민, 청원, 게시판, 섹스, 희, 주야, 이상, 글, 여기, 청원, 곳, 놈, ...  
1       392  [배틀, 그라운드, 세계, 우리, 나라, 흥행, 게임, 게임, 청소년, 이용, 불가...  
2       669  [적폐, 청산, 시금석, 양심수, 특별, 사면, 배제, 문재, 정부, 규탄, 월일,...  
3       284  [안녕, 독재, 시대, 대한민국, 민주, 열사, 민주, 유공자, 인정, 국가, 유공...  
4       167  [련, 야당, 질의, 관련, 기본, 유시민, 작가, 말씀, 동의, 국익, 관련, 정...

In [93]:
cols = ['begin', 'category', 'title', 'cont_noun', 'num_agree', 'new_status']
df3 = df3[cols]

In [94]:
df3.head()

begin  category                                            title  \
0  2018-01-01        행정                         아...이런데서 이상한 글이 올라오네요...   
1  2018-01-01        기타  현재 사람들 사이에서 유행하는 게임 "배틀 그라운드" 에 대한 제재를 가하려 합니다.   
2  2018-01-01      정치개혁                                  양심수 석방 국가보안법 철폐   
3  2018-01-01    인권/성평등                          민주화유공자들에 대한 국가유공자 인정 요청   
4  2018-01-01  외교/통일/국방                                           UAE 관련   

                                           cont_noun  num_agree  new_status  
0  [국민, 청원, 게시판, 섹스, 희, 주야, 이상, 글, 여기, 청원, 곳, 놈, ...          6           0  
1  [배틀, 그라운드, 세계, 우리, 나라, 흥행, 게임, 게임, 청소년, 이용, 불가...          1           0  
2  [적폐, 청산, 시금석, 양심수, 특별, 사면, 배제, 문재, 정부, 규탄, 월일,...          0           0  
3  [안녕, 독재, 시대, 대한민국, 민주, 열사, 민주, 유공자, 인정, 국가, 유공...          3           0  
4  [련, 야당, 질의, 관련, 기본, 유시민, 작가, 말씀, 동의, 국익, 관련, 정...          0           0

In [95]:
df3.to_pickle('petitions_df_ppt.pkl')

In [97]:
#DTM, tf-idf 생성
#sklearn 모듈이 인식할 수 있도록 시리즈 안에 리스트들을 str형태로 변환하는 작업 우선 수행
df3['cont_noun_str'] = df3.cont_noun.apply(lambda x: ','.join(x))

In [100]:
#DTM 생성
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer().fit_transform(df3['cont_noun_str'])

In [101]:
cv.toarray()

MemoryError: Unable to allocate array with shape (270836, 98486) and data type int64

In [110]:
#제약조건을 줘서 생성하기
#DTM 다시 생성
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features = 5000, max_df = 0.90, min_df = 5).fit(df3['cont_noun_str'])
cv_array = cv.transform(df3['cont_noun_str']).toarray()

In [111]:
print(cv_array)
print('\n',cv_array.shape) #27만개의 문서들이 5000개의 단어들로 표현된 행렬

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 0 0]]

 (270836, 5000)


In [112]:
cv.vocabulary_
    #단어들별로 정수인덱싱된것을 알 수 있음

{'국민': 569,
 '청원': 4190,
 '게시판': 218,
 '이상': 3234,
 '여기': 2759,
 '처벌': 4152,
 '세계': 2203,
 '우리': 2981,
 '나라': 792,
 '게임': 220,
 '청소년': 4187,
 '이용': 3244,
 '불가': 1853,
 '피시방': 4663,
 '플레이': 4656,
 '나이': 800,
 '제한': 3752,
 '제재': 3738,
 '지난번': 3957,
 '효과': 4954,
 '경찰관': 276,
 '신고': 2484,
 '출동': 4289,
 '생각': 2095,
 '폭력': 4624,
 '중독': 3899,
 '설정': 2175,
 '보호': 1733,
 '권리': 612,
 '침해': 4362,
 '현상': 4823,
 '관심': 471,
 '간청': 62,
 '적폐': 3573,
 '청산': 4185,
 '특별': 4511,
 '사면': 1959,
 '배제': 1603,
 '문재': 1432,
 '정부': 3682,
 '규탄': 629,
 '월일': 3057,
 '박근혜': 1516,
 '정권': 3668,
 '수감': 2306,
 '포함': 4619,
 '문재인': 1433,
 '제외': 3733,
 '누구': 925,
 '민중': 1500,
 '주도': 3838,
 '민주': 1497,
 '노총': 891,
 '위원장': 3069,
 '정치': 3707,
 '공작': 408,
 '내란': 844,
 '음모': 3149,
 '누명': 932,
 '의원': 3184,
 '사드': 1949,
 '배치': 1607,
 '반대': 1528,
 '세월호': 2221,
 '진상': 4038,
 '규명': 624,
 '탄압': 4414,
 '사람': 1950,
 '질서': 4057,
 '유린': 3100,
 '민생': 1489,
 '파탄': 4543,
 '세력': 2210,
 '저항': 3560,
 '촛불': 4232,
 '탄생': 4413,
 '석방': 2133,
 '요구':

In [113]:
#TF-IDF 생성
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer(max_features = 5000, max_df = 0.90, 
                     min_df = 5, sublinear_tf = True).fit_transform(df3['cont_noun_str'])

In [115]:
tv_array = tv.toarray()

In [118]:
#모델 학습

#1. 랜덤포레스트
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X = tv_array #tf-idf 행렬이 feature로 이용된다
y = df3.category #예측하고자 하는 것. 카테고리

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3,
                                                   stratify = y, random_state = 156)

In [120]:
#랜덤포레스트 모델 학습
rf_clf = RandomForestClassifier(n_jobs = -1, random_state = 156)
rf_clf.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=156)

In [124]:
from sklearn.metrics import classification_report

pred = rf_clf.predict(X_test)

print('랜덤 포레스트 모델 이용 카테고리 분류결과:\n',
     classification_report(y_test, pred, target_names = df3.category.unique()))

랜덤 포레스트 모델 이용 카테고리 분류결과:
               precision    recall  f1-score   support

          행정       0.50      0.38      0.43      3873
          기타       0.57      0.78      0.66      6550
        정치개혁       0.32      0.31      0.31      9715
      인권/성평등       0.60      0.13      0.22       410
    외교/통일/국방       0.63      0.56      0.59      4160
    교통/건축/국토       0.35      0.10      0.16      3765
        보건복지       0.75      0.74      0.75       818
         일자리       0.56      0.59      0.58      4895
          미래       0.43      0.07      0.12      1635
        농산어촌       0.53      0.46      0.49      5983
       육아/교육       0.56      0.66      0.61      6072
       경제민주화       0.59      0.79      0.67      4848
        성장동력       0.51      0.51      0.51      6539
 문화/예술/체육/언론       0.52      0.68      0.59      5078
        반려동물       0.50      0.14      0.21       713
       안전/환경       0.50      0.66      0.56     11889
   저출산/고령화대책       0.47      0.12      0.19      4308



In [126]:
#나이브 베이즈 분류기 모델 학습
from sklearn.naive_bayes import MultinomialNB

nb_clf = MultinomialNB()
nb_clf.fit(X_train, y_train)

MultinomialNB()

In [127]:
pred = nb_clf.predict(X_test)

print('나이브 베이즈 분류기 이용 카테고리 분류결과:\n',
     classification_report(y_test, pred, target_names = df3.category.unique()))

나이브 베이즈 분류기 이용 카테고리 분류결과:
               precision    recall  f1-score   support

          행정       0.46      0.40      0.43      3873
          기타       0.60      0.72      0.66      6550
        정치개혁       0.33      0.28      0.30      9715
      인권/성평등       0.74      0.16      0.27       410
    외교/통일/국방       0.65      0.59      0.62      4160
    교통/건축/국토       0.29      0.08      0.12      3765
        보건복지       0.83      0.71      0.77       818
         일자리       0.56      0.57      0.56      4895
          미래       0.37      0.12      0.18      1635
        농산어촌       0.50      0.53      0.51      5983
       육아/교육       0.58      0.65      0.61      6072
       경제민주화       0.64      0.71      0.67      4848
        성장동력       0.48      0.53      0.50      6539
 문화/예술/체육/언론       0.52      0.65      0.58      5078
        반려동물       0.55      0.21      0.31       713
       안전/환경       0.48      0.68      0.56     11889
   저출산/고령화대책       0.35      0.12      0.18      4308


In [2]:
#8.13
import pandas as pd
import numpy as np

df3 = pd.read_pickle('petitions_df3_ppt.pkl')

In [4]:
df3.new_status.value_counts()

0    270834
1         2
Name: new_status, dtype: int64

In [4]:
df3['cont_noun_str'] = df3.cont_noun.apply(lambda x: ','.join(x))

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer(max_features = 5000, max_df = 0.90, 
                     min_df = 5, sublinear_tf = True).fit_transform(df3['cont_noun_str'])

In [7]:
tv_array = tv.toarray()

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(tv_array, df3.category, test_size = 0.3,
                                                   stratify = df3.category, random_state = 156)

In [ ]:
#xgboost이용 모델 학습
from xgboost import XGBClassifier

xgbc = XGBClassifier(n_estimators = 200, n_jobs = -1)
xgbc.fit(X_train, y_train)
    #모델 학습이 진행되지 않음..

## TF-IDf

df(t) = 특정 단어 t가 등장한 **문서 d의 개수**   


idf = df(t)의 반비례하는 수
- 즉 특정단어가 여러 문서에서 등장할수록 idf값은 낮아진다
## $idf(d, t) = ln(\frac{n}{1+df(t)})$
    -여기서 n은 전체 문서의 개수



## $idf(문서3, 노란) = ln(\frac{4}{1+1})$

## $=  0.693147$
